### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy_codex#128]
If we do that, the Action can not update tool and tutorial lists

Possible solution
- Protect main and have PR with changes instead of pushing directly 

     But someone needs to merge the PR every week

- Allow only the CI to push directly
   
    Not sure how to do that

- Store the results in a different repo (as the research-software-ecosystem does)

**Comment by bebatut** [comment]
I like @nsoranzo's idea!

**Comment by paulzierep** [comment]
I agree that would work, but is it not a somewhat strange way of using git ? :)

**Comment by paulzierep** [comment]
I did re-protect the main branch again, btw., I only unprotected to show in the demo how the CI is working.

**Comment by nsoranzo** [comment]
It is the way GitHub Pages use the gh-pages branch, see e.g. https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

This is how I do it in my repo: https://github.com/TGAC/rfparser/blob/main/.github/workflows/deploy.yaml

**Comment by paulzierep** [comment]
@nsoranzo it seems that storing the results in a different branch does bring some new issues: https://github.com/galaxyproject/galaxy_codex/actions/runs/10338185162/job/28615936668 
Maybe you have an idea how to handle this ?

**Comment by paulzierep** [comment]
I think that should do the trick, https://github.com/galaxyproject/galaxy_codex/pull/163

**Comment by kostrykin** [comment]
> * Allow only the CI to push directly
>   Not sure how to do that

Should be possible using a deploy key (you can use exceptions from protection for deploy keys)

**Comment by paulzierep** [comment]
Is fixed now, as the CI makes a PR for the updated stats.
