### ISSUE TITLE
Restructure codex for community content

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy_codex#164]
As discussed with @bebatut and @nomadscientist. The repo seems to be laid out in a way that is friendly for developers, but not so much for community (potential non-coding) users.

It would be great if we could do a restructure of the repo to improve this. Since it is supposed to be a place for community members to access metadata, I suggest something like:

```
bin/
    *.sh
    *.py
    README.md
communities/
    microgalaxy/  # If I'm a MicroGalaxy user, everything I need is in here
        lab/
        metadata/
    singlecell/
        [...]
    [...]
README.md
```

Where:

1. The current README.md is moved to ./bin/README.md.
2. A new README, aimed at community users, is written at ./README.md, as suggested in #147.
3. Results from metadata extractor are written to `communities/<name>/metadata/`.
4. Lab (aka subdomain) content is written to `communities/<name>/lab/`.

I don't mind doing some of the work here, for now I'm just hoping for a bit of discussion on this. Thanks!

**Comment by paulzierep** [comment]
In the new structure we also need to find a place to store the stuff in https://github.com/galaxyproject/galaxy_codex/tree/main/data

**Comment by paulzierep** [comment]
> 4. Lab (aka subdomain) content is written to `communities/<name>/lab/`.
 Is this automatically created? These are only config files created individually correct ?

**Comment by neoformit** [comment]
> Is this automatically created?
Nope, these are written manually to create a new Lab page
