### ISSUE TITLE
Review column names in tool table

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy_codex#170]
The current names of columns in the [tool table](https://github.com/galaxyproject/galaxy_codex/blob/results/all_tools.tsv) need to be rethought.
We started the work in the following spreadsheet: https://docs.google.com/spreadsheets/d/1_LTgWFJ1LVaBy75xJWopOl7SdbYjdNWYpVXX1VZMDtk/edit?gid=0#gid=0

If you have suggestions for new names or comments, please add them to the spreadsheet before October 1st
Thanks a lot for your help!

**Comment by kostrykin** [comment]
I was confused by the current columns `Galaxy Wrapper ID` und `Galaxy Tool ID`, like what's the difference.

The spreadsheet suggests that the former is the Suite ID and should be renamed accordingly. But this raises the next question: What is a Suite ID, in the first place? Like, for example, we have numerous wrappers for `scikit-image`. Should this be considered a Suite? However, there is no Suite ID for `scikit-image`, that I'm aware of.

Does conflict with the suggested terminology? How does the situation with the `scikit-image` wrappers map to the suggested terminology?
