### ISSUE TITLE
[Feature request] Galaxy Labs - track uses

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy_codex#213]
It would be amazing to track how many different servers/instances are using each subdomain/Galaxy Lab, i.e. "This subdomain is currently hosted on X instances, and here's the list"
@neoformit

**Comment by neoformit** [comment]
Hmm we might be able to track that by storing the request headers in the labs engine. Can you open this issue there instead please? [usegalaxy-au/galaxy-labs-engine](https://github.com/usegalaxy-au/galaxy-labs-engine)

**Comment by nomadscientist** [comment]
Done!
Added here https://github.com/usegalaxy-au/galaxy-labs-engine/issues/7
