### ISSUE TITLE
Button images do not work on Safari

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy_codex#227]
@neoformit 
<img width="616" alt="Screenshot 2024-11-07 at 11 12 54" src="https://github.com/user-attachments/assets/9f4ee555-09d6-49b9-9fb3-1e8a522e6d2c">

**Comment by neoformit** [comment]
:eyes:

**Comment by neoformit** [comment]
Resolved with https://github.com/usegalaxy-au/galaxy-labs-engine/pull/17
