### ISSUE TITLE
Lab export fix, local dev ? 

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy_codex#235]
It seems that the lab/export does only after a while loads the latest content of the repository and in this case it gives an Server Error

https://site.usegalaxy.org.au/lab/export?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml

@neoformit any idea ?

**Comment by neoformit** [comment]
Hi Paul, please use the Lab Engine server, this is no longer maintained on site.usegalaxy.org.au (the Media Site):

https://labs.usegalaxy.org.au/?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml

Looks good to me! The server caches these pages, so if you are in development please add `&cache=false` to the URL:

https://labs.usegalaxy.org.au/?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml&cache=false

**Comment by paulzierep** [comment]
Thanks the cache parameter is really useful ! However we should add to the documentation, that actually github .raw can be the issue as well: https://github.com/orgs/community/discussions/46691 :)

**Comment by paulzierep** [comment]
Still, it seems, that sometime especially the sections seem not to render directly. E.g. this
https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/sections/5_tools.yml is not rendered, even with the cache option: https://labs.usegalaxy.org.au/?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml&cache=false

**Comment by paulzierep** [comment]
OK working now, seems to be some lack between GitHub, GitHub Raw Data and the Engine Server!

**Comment by neoformit** [comment]
Thanks Paul, yes there are multiple layers of caching with github raw content being cached for 300s. It can be problematic but I don't think I've experienced more than a few moment's delay in the past! I have doc'd this but it's not yet deployed on labs.usegalaxy.org.au.

**Comment by neoformit** [comment]
Ok, this is now in the "How do I make one" dropdown on the docs page

![image](https://github.com/user-attachments/assets/52367f96-e85d-438c-b693-e37f6e0a3334)
