### ISSUE TITLE
Add table with search function to labs

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy_codex#236]
Not sure, maybe this can already be set up, but some labs will have 100+ tools, is there a way to add tables that can be searched ?

**Comment by paulzierep** [comment]
For example, such a table: https://github.com/paulzierep/galaxy_tool_extractor/blob/443f6cca8e374b3a02151cb9a98b293d7f276f79/communities/microgalaxy/lab/sections/5_tools.yml would require some improved UI ...

**Comment by paulzierep** [comment]
Here is the rendered version: https://labs.usegalaxy.org.au/?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml&cache=false

How much could the table be customized, is this possible via the yaml, docs available ? I think at least a search option, a condensed view and maybe a way to show optional data, like only show some metadata on click, would be needed ?

**Comment by paulzierep** [comment]
@neoformit any idea about that ?

**Comment by neoformit** [comment]
The idea of the Labs page is not to show the user ALL of the available tools. That is what the tool panel is for. 

The idea of a Lab page is to show the user something more concise than the 100s of tools in the tool box, in a format that allows the user to learn why they are important or best-practice. Use the Sections/Tabs to break tools into different categories that the user can navigate to fulfil their journey.

You should use this list to create a tool panel view instead (see SPOC lab for an example).

**Comment by paulzierep** [comment]
Well, I think @bebatut  and me have a different view on this. Maybe we should have a CoDex meeting at some point to talk about this ?

**Comment by paulzierep** [comment]
To explain, we would like to show the complete resources of microGalaxy at a central place. This includes also tools that are useful but not necessary installed on a specific server (unfortunately, it will be a long way on the road that servers are truly synchronized). Otherwise, we would need to add the tool list somewhere else. Which would be confusing for users too and even worse for reviewers.

Also if we have a lot of workflows we have the same issue.
Any chance to get a search UI or something ?

**Comment by neoformit** [comment]
Sure, that is possible but it sounds like you're asking the Labs Engine to be a MicroGalaxy ToolShed. Maybe that's a cool idea but it sounds out-of-scope to me. If you want to make a web page that does this, feel free to build a github.io page and link/embed in your Lab page. You can render the HTML from your metadata extractor so it's auto-generated, and do the search bar with some basic javascript.

For Labs Engine development, a much higher priority is this PR which enables Galaxy Lab PRs to be tested: https://github.com/galaxyproject/galaxy_codex/pull/201 
Without this, Labs pages are likely to break when untested PRs are merged. I can't merge this PR without an approving review and appropriate permissions to create a GitHub token for galaxy_codex (or someone else willing to make a token on my behalf).

**Comment by neoformit** [comment]
To be clear - *you can already include custom HTML snippets* in your Lab page. This is enough to build the feature that you are asking for. It's not the job of the Labs Engine to provide every web component that might be useful in a Galaxy Lab. If you want something fancy, some web development is required. If you think this is something every Lab might benefit from, you are welcome to make a pull request to [usegalaxy-au/galaxy-labs-engine](https://github.com/usegalaxy-au/galaxy-labs-engine).

Tool metadata as JSON (this can live anywhere in the repo):
```js
[
    {
        "tool_name": "Kraken2",
        "tool_description": "Taxonomic classification of metagenomic sequences."
    },
    {
        "tool_name": "MetaPhlAn",
        "tool_description": "Profiling the composition of microbial communities."
    },
    {
        "tool_name": "FastQC",
        "tool_description": "Quality control tool for high throughput sequence data."
    }
]
```

HTML snippet (include in your Lab's `conclusion.html`):
```html
<div>
    <table id="toolsTable">
        <thead>
            <tr>
                <th>Tool Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            <!-- Rows will be dynamically inserted here -->
        </tbody>
    </table>

    <script>
        const JSON_URL = 'https://raw.githubusercontent.com/galaxyproject/galaxy_codex/refs/heads/main/communities/microgalaxy/metadata/tools.json'
        async function fetchAndRenderTools() {
            try {
                // Fetch the JSON file
                const response = await fetch(JSON_URL);
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }

                const tools = await response.json();

                // Reference the table body
                const tableBody = document.getElementById('toolsTable').querySelector('tbody');

                // Populate the table with tools
                tools.forEach(tool => {
                    const row = document.createElement('tr');
                    row.innerHTML = `
                        <td>${tool.tool_name}</td>
                        <td>${tool.tool_description}</td>
                    `;
                    tableBody.appendChild(row);
                });
            } catch (error) {
                console.error('Error fetching or rendering tools:', error);
            }
        }

        // Call the function to fetch and render tools
        fetchAndRenderTools();
    </script>
</div>
```
