### ISSUE TITLE
Title formatting

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy_codex#243]
<img width="461" alt="Screenshot 2024-11-21 at 22 06 21" src="https://github.com/user-attachments/assets/61eeaa7f-98d0-478e-a9d6-cc7c09c09a50">

The title font / size / shape steals a lot of space on a narrow computer. Is there a way around this? It doesn't look great

**Comment by nomadscientist** [comment]
<img width="868" alt="Screenshot 2024-11-21 at 22 10 33" src="https://github.com/user-attachments/assets/7b665ad1-eab1-49f8-8472-20ac0ad25b32">

**Comment by neoformit** [comment]
Resolved with https://github.com/usegalaxy-au/galaxy-labs-engine/pull/17
