### ISSUE TITLE
Single-cell image

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy_codex#244]
@neoformit any idea where our single-cell image went? It's now not working in the title / top of the Lab page

**Comment by nomadscientist** [comment]
Specifically in singlecell.usegalaxy.eu

**Comment by neoformit** [comment]
Not sure what image you mean. I see this?

![image](https://github.com/user-attachments/assets/a45f6348-9dc9-47da-8aee-3ac3682abd11)

**Comment by neoformit** [comment]
That is strange - maybe a Github issue :thinking: as I think that's where your browser fetches the image from.
