### ISSUE TITLE
How often does the lab deploy updates

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy_codex#266]
Without `cache=false`: `https://labs.usegalaxy.org.au/?content_root=https://raw.githubusercontent.com/paulzierep/galaxy_tool_extractor/refs/heads/microgalaxy_lab/communities/microgalaxy/lab/base.yml&cache=false` updates to the lab need a while to propagate to deployment: 
https://microgalaxy.usegalaxy.eu/

How often are the pages newly generates ? @neoformit ?

**Comment by neoformit** [comment]
For now the cache time is 1 hour.
When [this PR](https://github.com/galaxyproject/galaxy_codex/pull/201) merges, change made via galaxy_codex PR will appear as soon as the GitHub workflow completes, and I will set the cache time to forever (until a request is made with `cache=false`, either by human or GH workflow).
